# Local build: packages a pre-built host binary (bin/manager) onto distroless.
# Use this when the golang builder image cannot be pulled. Build the binary with:
#   CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o bin/manager ./cmd
FROM gcr.io/distroless/static:nonroot
WORKDIR /
COPY bin/manager /manager
USER 65532:65532
ENTRYPOINT ["/manager"]
